Repository tsumiki-works/Pyramid, pull requests merged in 2022-12, with the labels that each got.

#146 Blockクラスの抽象化
  .github/workflows/deploy-when-pr.yml
  ts/block/atom_block.ts
  ts/block/block.ts
  ts/block/block_formatter.ts
  ts/block/concrete_block/bool_block.ts
  ts/block/concrete_block/f32_block.ts
  ts/block/concrete_block/fun_block.ts
  ts/block/concrete_block/i32_block.ts
  ts/block/concrete_block/list_block.ts
  ts/block/concrete_block/string_block.ts
  ts/block/full_block.ts
  ts/menu/menu.ts
  ts/pyramid_engine/pyramid_playground.ts
Labels: backend

#178 i32とf32をまとめてNumberに演算をまとめた
  ts/block/concrete_block/define_block.ts
  ts/evaluation/i32.ts
  ts/evaluation/operator.ts
  ts/evaluation/operator_test.ts
  ts/evaluation/pyramid_math.ts
  ts/evaluation/pyramid_number.ts
  ts/keywords.ts
  ts/main.ts
  ts/pyramid_engine/pyramid_playground.ts
  ts/pyramid_engine/tutorial_database.ts
  ts/types.ts
Labels: hurry

#183 evaluationモジュールの整備
  ts/block/basic_block.ts
  ts/evaluation/arithmetic_operator.ts
  ts/evaluation/bool.ts
  ts/evaluation/evaluator.ts
  ts/evaluation/logical_operator.ts
  ts/evaluation/math_function.ts
  ts/evaluation/pyramid_number.ts
  ts/evaluation/string.ts
  ts/keywords.ts
  ts/pyramid_engine/tutorial_database.ts
Labels: backend

#185 結果表示の実装 dev/show\-result
  index.html
  style.css
  ts/block/basic_block.ts
  ts/block/block.ts
  ts/block/event_block.ts
  ts/block/parent_block.ts
  ts/console_manager.ts
  ts/main.ts
  ts/menu/menu_block.ts
  ts/popup.ts
  ts/pyramid_engine/pyramid_playground.ts
  tutorial/playground/index.html
Labels: enhancement, frontend

#212 symbolとしてπを追加
  ts/keywords.ts
  ts/pyramid_engine/tutorial_database.ts
Labels: enhancement

#216 stringの等価比較演算子を用意した
  ts/evaluation/comparison_operator.ts
  ts/keywords.ts
  ts/pyramid_engine/tutorial_database.ts
Labels: enhancement

#222 Dev/add i32 f32
  style.css
  ts/block/binop_block.ts
  ts/block/concrete_block/define_block.ts
  ts/block/concrete_block/list/map_block.ts
  ts/block/concrete_block/operator/add_block.ts
  ts/block/concrete_block/operator/float_div.ts
  ts/block/concrete_block/operator/int_div.ts
  ts/block/concrete_block/operator/mod_block.ts
  ts/block/concrete_block/operator/mul_block.ts
  ts/block/concrete_block/operator/pow_block.ts
  ts/block/concrete_block/operator/sub_block.ts
  ts/block/inference/typeenv.ts
  ts/evaluation/arithmetic_operator.ts
  ts/evaluation/evaluator.ts
  ts/evaluation/f32.ts
  ts/evaluation/i32.ts
  ts/evaluation/math_function.ts
  ts/keywords.ts
  ts/pyramid_engine/tutorial_database.ts
  ts/types.ts
Labels: backend
